
import React from "react";
import PageTransition from "@/components/transitions/PageTransition";

const Terms: React.FC = () => {
  return (
    <PageTransition>
      <div className="max-w-3xl mx-auto px-6 py-32">
        <div className="text-center mb-12">
          <h1 className="text-3xl sm:text-4xl font-bold mb-4">
            Terms & Conditions
          </h1>
          <p className="text-muted-foreground">
            Last Updated: April 2025
          </p>
        </div>
        
        <div className="prose prose-blue max-w-none">
          <p className="text-lg">
            Please read these Terms and Conditions carefully before using the Snow Day Calculator website.
            By using our website, you agree to comply with and be bound by these Terms and Conditions.
          </p>
          
          <h2 className="text-2xl font-semibold mt-10 mb-4">Use of the Snow Day Calculator</h2>
          
          <p>
            The Snow Day Calculator is provided for informational and entertainment purposes only.
            The predictions and probabilities generated by our calculator are estimates based on
            weather data and should not be considered official information regarding school closures.
          </p>
          
          <p>
            School closure decisions are made by your local school district, not by this website.
            Always check with your school or district for official announcements regarding closures.
          </p>
          
          <h2 className="text-2xl font-semibold mt-10 mb-4">No Guarantee of Accuracy</h2>
          
          <p>
            While we strive to provide accurate information, we cannot guarantee the accuracy of
            the weather data or the predictions made by our calculator. Weather conditions can
            change rapidly, and many factors beyond our calculations may influence school closure decisions.
          </p>
          
          <p>
            By using this site, you acknowledge and agree that all predictions are just estimates
            based on available weather data and our calculation algorithm.
          </p>
          
          <h2 className="text-2xl font-semibold mt-10 mb-4">Intellectual Property</h2>
          
          <p>
            All content, features, and functionality of the Snow Day Calculator website, including
            but not limited to text, graphics, logos, icons, images, and software, are the exclusive
            property of Snow Day Calculator and are protected by United States and international
            copyright, trademark, and other intellectual property laws.
          </p>
          
          <h2 className="text-2xl font-semibold mt-10 mb-4">User Conduct</h2>
          
          <p>
            You agree not to use the Snow Day Calculator for any unlawful purpose or in any way
            that could damage, disable, overburden, or impair the site or interfere with any other
            party's use of the site.
          </p>
          
          <h2 className="text-2xl font-semibold mt-10 mb-4">Third-Party Links</h2>
          
          <p>
            Our website may contain links to third-party websites or services that are not owned
            or controlled by Snow Day Calculator. We have no control over, and assume no responsibility
            for, the content, privacy policies, or practices of any third-party websites or services.
          </p>
          
          <h2 className="text-2xl font-semibold mt-10 mb-4">Limitation of Liability</h2>
          
          <p>
            In no event shall Snow Day Calculator, its operators, or any related parties be liable
            for any indirect, incidental, special, consequential, or punitive damages, including
            without limitation, loss of profits, data, use, goodwill, or other intangible losses,
            resulting from:
          </p>
          
          <ul>
            <li>Your access to or use of or inability to access or use the site</li>
            <li>Any conduct or content of any third party on the site</li>
            <li>Any content obtained from the site</li>
            <li>Unauthorized access, use, or alteration of your transmissions or content</li>
          </ul>
          
          <h2 className="text-2xl font-semibold mt-10 mb-4">Changes to Terms</h2>
          
          <p>
            We reserve the right, at our sole discretion, to modify or replace these Terms at any time.
            If a revision is material, we will make reasonable efforts to provide at least 30 days'
            notice prior to any new terms taking effect.
          </p>
          
          <h2 className="text-2xl font-semibold mt-10 mb-4">Contact Us</h2>
          
          <p>
            If you have any questions about these Terms, please contact us at:{" "}
            <a href="mailto:support@snowdaycalculator.com" className="text-primary hover:underline">
              support@snowdaycalculator.com
            </a>
          </p>
        </div>
      </div>
    </PageTransition>
  );
};

export default Terms;
